name: Test Flask App with PostgreSQL

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: c0917329
          POSTGRES_PASSWORD: pass123
          POSTGRES_DB: mydb
        ports:
          - 5432:5432
        options: >-
          --name c0917329-db
          --health-cmd="pg_isready -U c0917329"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Wait for PostgreSQL
        run: sleep 15

      - name: Install PostgreSQL client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Initialize database schema
        run: |
          PGPASSWORD=pass123 psql -h localhost -U c0917329 -d mydb -c "
            CREATE TABLE IF NOT EXISTS users (
              id SERIAL PRIMARY KEY,
              name VARCHAR(50)
            );
            INSERT INTO users (name) VALUES ('Alice'), ('Bob'), ('Carlos');
          "

      - name: Run Flask app container
        run: |
          docker run -d --name c0917329-app \
            -p 5000:5000 \
            secarl/cbd3345-ica1

      - name: Wait for app to start
        run: sleep 10

      - name: Test root endpoint
        run: curl --fail http://localhost:5000 || exit 1

      - name: Test /users endpoint
        run: curl --fail http://localhost:5000/users || exit 1
